### ISSUE TITLE
Error on injection

### ISSUE THREAD

**Issue by amarCosmospace** [Technowlogy-Pushpender/apkinfector#3]
[*] Trying to Find .smali File of Launcher
Traceback (most recent call last):
  File "infector.py", line 319, in <module>
    hook_meterpreter_in_apk(VAR1, VAR2, VAR3)
  File "infector.py", line 177, in hook_meterpreter_in_apk
    launcherActivity = str(launcherActivity).split('\'')[1]
IndexError: list index out of range

Any idea ?

Good Job btw

**Comment by PushpenderIndia** [comment]
APKinfector is unable to find the hook point in your case, I have fixed a
minor issue.

So try it again, you might be prompt to enter the launcher activity
manually from the AndroifManifest.xml if the script is unable to find it
manually

**Comment by amarCosmospace** [comment]
Yes, thanks for your work :)

**Comment by devilboy081120** [comment]
Trying to Find .smali File of Launcher                                                                          
Traceback (most recent call last):                                                                                  
  File "/home/kali/apkinfector/infector.py", line 322, in <module>                                                  
    hook_meterpreter_in_apk(VAR1, VAR2, VAR3)                                                                       
  File "/home/kali/apkinfector/infector.py", line 167, in hook_meterpreter_in_apk                                   
    lineNumber = int(lineNumber.decode().split('\n')[0]) - 1                                                        
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                            
ValueError: invalid literal for int() with base 10: '' 



i have same issue how can i solve it
                            please help
