### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ghost** [Technowlogy-Pushpender/apkinfector#8]
[*] Changing default folder and filenames being flagged by AV
[+] Changed Successfully!

[*] Moving Meterpreter Payload to Normal/Legitimate APK
[+] Moved Successfully!

[*] Trying to Find .smali File of Launcher
Traceback (most recent call last):
  File "/root/apkinfector/infector.py", line 322, in <module>
    hook_meterpreter_in_apk(VAR1, VAR2, VAR3)
  File "/root/apkinfector/infector.py", line 167, in hook_meterpreter_in_apk
    lineNumber = int(lineNumber.decode().split('\n')[0]) - 1
ValueError: invalid literal for int() with base 10: ''

Do you have any idea?

**Comment by ghost** [comment]
I solved the problem.
Thanks for your perfect code!!!
